services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ecoropa
      POSTGRES_PASSWORD: ecoropa
      POSTGRES_DB: ecoropa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    command: >-
      sh -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://ecoropa:ecoropa@db:5432/ecoropa
      SECRET_KEY: "super-secret"
      ACCESS_TOKEN_EXPIRE_MINUTES: 120
    ports:
      - "8000:8000"
volumes:
  postgres_data:
